server.port=8080
spring.application.name=random-jokes

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/jokesdb
spring.datasource.username=jokes
spring.datasource.password=jokes123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect
spring.jpa.show-sql=false

# External Jokes API
jokes.api.base-url=https://v2.jokeapi.dev
